#### 服务配置文件示例
SERVER_NAME: AgentPlatform //服务名称
SERVER_ENV: local //环境名称
SERVER_DEBUG: true //开发模式
SERVER_HOST: 0.0.0.0 //监听地址
SERVER_PORT:  //监听端口

TIMEZONE: Asia/Shanghai //时区
SERVER_AUTH_ENABLE: true // 鉴权开关
SERVER_AUTH_KEY: X-Api-Key // 鉴权字段
SERVER_AUTH_CACHE_TTL: 1800 // 鉴权缓存时间

DB_CONNECTION: postgres //数据库类型
DB_HOST: //数据库地址
DB_PORT: //数据库端口
DB_DATABASE: //数据库名称
DB_USERNAME: //数据库用户名
DB_PASSWORD: //数据库密码
DB_MAX_IDLE_CONNECTIONS: 10 //数据库最大空闲连接数
DB_MAX_OPEN_CONNECTIONS: 20 //数据库最大打开连接数
DB_MAX_LIFE_SECONDS: 300 //数据库连接最大生命周期
DB_SSLMODE: disable //数据库SSL模式
  
LOG_LEVEL: debug //日志等级
LOG_TYPE: console //日志类型 只有一个 console 选项

REDIS_ENABLE: true
REDIS_ADDR: 127.0.0.1:6379
REDIS_USERNAME:
REDIS_PASSWORD:
REDIS_DB: 0
REDIS_POOL_SIZE:
REDIS_MIN_IDLE_CONNS:
REDIS_MAX_RETRIES:
REDIS_DIAL_TIMEOUT_SECONDS: